# Generated by Django 2.0.1 on 2018-02-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180130_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Table 0', max_length=25)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='allergy',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='menu',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
