# Generated by Django 2.0.1 on 2018-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180207_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='seating',
            name='assistance',
            field=models.BooleanField(default=False),
        ),
    ]
