# Generated by Django 2.0.1 on 2018-02-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_seating_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
