# Generated by Django 2.0.1 on 2018-02-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.CharField(default='na', max_length=1000),
        ),
    ]
