# Generated by Django 2.0.1 on 2018-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180227_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
