# Generated by Django 2.0.2 on 2018-03-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20180305_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.CharField(default='na', max_length=1000),
        ),
    ]
