# Generated by Django 2.0.2 on 2018-03-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20180305_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meat',
            field=models.BooleanField(default=False),
        ),
    ]
