# Generated by Django 2.0.2 on 2018-03-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_menu_meat'),
        ('customer', '0007_menu_stock'),
    ]

    operations = [
    ]
