# Generated by Django 2.0.2 on 2018-03-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_merge_20180307_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='seating',
            name='waiter',
            field=models.CharField(default='', max_length=50),
        ),
    ]
