# Generated by Django 2.0.2 on 2018-03-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_merge_20180307_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
