# Generated by Django 2.0.2 on 2018-03-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_menu_removed'),
        ('customer', '0011_seating_waiter'),
    ]

    operations = [
    ]
