# Generated by Django 2.0.2 on 2018-03-19 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('cooking_instructions', models.CharField(default='na', max_length=500)),
                ('purchase_method', models.CharField(default='na', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('ready_delivery', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('delayed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(default='na', max_length=50)),
                ('card_number', models.CharField(default='na', max_length=16)),
                ('cvc', models.CharField(default='na', max_length=3)),
                ('expiry', models.CharField(default='na', max_length=5)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('payment_requested', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('payment_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onduty', models.BooleanField(default=False)),
                ('name', models.CharField(default='waiter1', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='orderextra',
            name='items',
            field=models.ManyToManyField(to='waiter.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderextra',
            name='seating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Seating'),
        ),
        migrations.AddField(
            model_name='orderextra',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='waiter.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waiter.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Seating'),
        ),
    ]
