# Generated by Django 2.0.2 on 2018-03-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(default='na', max_length=100)),
                ('time', models.DateTimeField()),
                ('items', models.CharField(default='na', max_length=1000)),
                ('cooking_instructions', models.CharField(default='na', max_length=500)),
                ('purchase_method', models.CharField(default='na', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('ready_delivery', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='na', max_length=50)),
                ('card_holder', models.CharField(default='na', max_length=50)),
                ('card_number', models.CharField(default='na', max_length=12)),
                ('cvc', models.CharField(default='na', max_length=3)),
                ('expiry', models.CharField(default='na', max_length=5)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('payment_requested', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('payment_accepted', models.BooleanField(default=False)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Seating')),
            ],
        ),
    ]
