# Generated by Django 2.0.2 on 2018-03-05 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='customer.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Seating'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='table',
            field=models.CharField(default='na', max_length=50),
        ),
    ]
