# Generated by Django 2.0.2 on 2018-03-06 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Seating'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Seating'),
        ),
    ]
