# Generated by Django 2.0.2 on 2018-03-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_auto_20180306_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='table',
        ),
    ]
