# Generated by Django 2.0.2 on 2018-03-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_auto_20180309_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default='na', max_length=16),
        ),
    ]
