# Generated by Django 2.0.1 on 2018-02-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_remove_order_table_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
