# Generated by Django 2.0.2 on 2018-03-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0004_auto_20180307_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
