# Generated by Django 2.0.1 on 2018-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0005_auto_20180305_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onduty', models.BooleanField(default=False)),
                ('name', models.CharField(default='waiter1', max_length=50)),
            ],
        ),
    ]
