# Generated by Django 2.0.2 on 2018-03-06 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_auto_20180227_2153'),
        ('waiter', '0005_auto_20180305_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='waiter.OrderItem')),
                ('seating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Seating')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
