# Generated by Django 2.0.2 on 2018-03-08 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0006_orderextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderextra',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 16, 24, 21, 316981, tzinfo=utc)),
        ),
    ]
