# Generated by Django 2.0.2 on 2018-03-09 08:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0007_orderextra_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(default='na', max_length=50)),
                ('card_number', models.CharField(default='na', max_length=16)),
                ('cvc', models.CharField(default='na', max_length=3)),
                ('expiry', models.CharField(default='na', max_length=5)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('payment_requested', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('payment_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Seating'),
        ),
        migrations.AlterField(
            model_name='orderextra',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 8, 41, 26, 296464, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waiter.Payment'),
        ),
    ]
