# Generated by Django 2.0.2 on 2018-03-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0006_waiter'),
        ('waiter', '0008_auto_20180309_0841'),
    ]

    operations = [
    ]
