# Generated by Django 2.0.1 on 2018-03-09 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0008_auto_20180309_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderextra',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 10, 31, 18, 516801, tzinfo=utc)),
        ),
    ]
