# Generated by Django 2.0.2 on 2018-03-13 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0009_auto_20180313_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextra',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 20, 19, 8, 45964, tzinfo=utc)),
        ),
    ]
