# Generated by Django 2.0.2 on 2018-03-13 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_merge_20180307_2003'),
        ('waiter', '0009_merge_20180313_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='seating',
            field=models.ManyToManyField(to='customer.Seating'),
        ),
        migrations.AlterField(
            model_name='orderextra',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
