# Generated by Django 2.0.2 on 2018-03-14 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0010_auto_20180313_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextra',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 13, 4, 0, 710367, tzinfo=utc)),
        ),
    ]
