# Generated by Django 2.0.2 on 2018-03-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0010_auto_20180313_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='seating',
        ),
    ]
