# Generated by Django 2.0.2 on 2018-03-19 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0011_auto_20180314_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextra',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 10, 58, 42, 979165, tzinfo=utc)),
        ),
    ]
