# Generated by Django 2.0.2 on 2018-03-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0011_remove_waiter_seating'),
        ('waiter', '0009_auto_20180309_1031'),
        ('waiter', '0009_auto_20180314_2138'),
    ]

    operations = [
    ]
