# Generated by Django 2.0.1 on 2018-01-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(default='na', max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('items', models.CharField(default='na', max_length=1000)),
                ('cooking_instructions', models.CharField(default='na', max_length=500)),
                ('purchase_method', models.CharField(default='na', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered', models.BooleanField(default=False)),
                ('table_assistance', models.BooleanField(default=False)),
            ],
        ),
    ]
