# Generated by Django 2.0.1 on 2018-01-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Order',
        ),
    ]
