# Generated by Django 2.0.1 on 2018-02-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_assistance',
        ),
    ]
