# Generated by Django 2.0.1 on 2018-01-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_auto_20180122_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='orderNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.BooleanField(default=False),
        ),
    ]
