# Generated by Django 2.0.1 on 2018-01-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0004_auto_20180124_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_taken',
        ),
    ]
