# Generated by Django 2.0.1 on 2018-01-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0005_remove_order_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderStatus',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='n', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_contents',
            field=models.CharField(default='n', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_method',
            field=models.CharField(default='n', max_length=100),
        ),
    ]
