# Generated by Django 2.0.1 on 2018-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0006_auto_20180124_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cooking_instructions',
            field=models.CharField(default='notavaliable', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='notavaliable', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_contents',
            field=models.CharField(default='notavaliable', max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_method',
            field=models.CharField(default='notavaliable', max_length=100),
        ),
    ]
