# Generated by Django 2.0.1 on 2018-01-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0007_auto_20180124_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cooking_instructions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_contents',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purchase_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
