# Generated by Django 2.0.1 on 2018-01-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0010_order_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_taken',
        ),
    ]
