# Generated by Django 2.0.1 on 2018-01-24 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0011_remove_order_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_taken',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 21, 56, 11, 656382, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
